name: Pipeline

on:
# despliegue por eventos
  push:
    branches:
      - develop
      - release
      - staging
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - develop
      - release
      - staging
      - main
# despliegue a demanda
  workflow_dispatch:
    
jobs:
    GitFlow-Check:
      name: GitFlow check 
      if: ${{ github.event_name == 'pull_request' }}
      runs-on: ubuntu-latest
      steps:
        - name: Deploy
          run: echo gitflow_check
            
    Snyk-IaC:
      name: Snyk  IaC
      if: ${{ github.event_name == 'pull_request' }}
      needs: [GitFlow-Check]
      runs-on: ubuntu-latest
      steps:
        - name: Deploy
          run: echo Snyk - IaC
                  
    Snyk-Code:
      name: Snyk  Code
      needs: [GitFlow-Check]
      if: ${{ github.event_name == 'pull_request' }}
      runs-on: ubuntu-latest
      steps:
        - name: Deploy
          run: echo Snyk - Code

    Test-unit:
      name: Snyk  Code
      if: |
        (github.event_name == 'workflow_dispatch' && (startsWith(github.ref, 'refs/heads/feature/') || startsWith(github.ref, 'refs/heads/hotfix/'))) ||
        github.event_name == 'pull_request'
      runs-on: ubuntu-latest
      steps:
         - name: Test unit
           run: echo Test unit
         - name: Sonar Scan Code
           run: echo Scan Code
      
    Snyk-Open-Source:
     name: Snyk - Open Source
     needs: [GitFlow-Check]
     if: ${{ github.event_name == 'pull_request' }}
     runs-on: ubuntu-latest
     steps:
       - name: Deploy
         run: Snyk - Open Source
      
