# name: CI + CD

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
#   workflow_dispatch:

# jobs:
#   Build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2

#       - name: Compile
#         run: echo Hello, world!
    
#   DeployDev:
#     name: Deploy to Dev 
#     if: github.event_name == 'pull_request'
#     needs: [Build]
#     runs-on: ubuntu-latest
#     environment: 
#       name: dev
#       url: 'http://dev.myapp.com'
#     steps:
#       - name: Deploy
#         run: |
#           echo "el secreto de ambiente dev es " ${{ secrets.SECRET_DEV }}

#   aprobQA:
#     name: approval to deploy
#     if: github.event.ref == 'refs/heads/main'
#     needs: [Build]
#     runs-on: ubuntu-latest
#     environment: 
#       name: qa
#     steps:
#       - name: aprob_QA
#         run: echo se permite el despliegue
            
#   DeployProd:
#     name: Deploy to Production 
#     needs: [aprobQA]
#     runs-on: ubuntu-latest
#     environment: 
#       name: Production
#       url: 'http://www.myapp.com'
#     steps:
#       - name: Deploy
#         run: echo I am deploying! 
    